### ISSUE TITLE
`poetry install` fail with Python 3.9.7

### ISSUE THREAD

**Issue by inpefess** [sberbank-ai-lab/RePlay#4]
Works well for Python 3.7.11, but for 3.9.7 hangs on `pandas`

**Comment by Darel13712** [comment]
Tried building it and now it installed succesfully. Here's the [run](github.com/sberbank-ai-lab/RePlay/runs/4166705870). Can you reproduce this now?

**Comment by inpefess** [comment]
Now I see the following:

```sh
% poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  Because replay-rec depends on docutils (=0.16) which doesn't match any versions, version solving failed.
```

**Comment by Darel13712** [comment]
This is strange, because Github was able to install it. Can you try running `pip install docutils==0.16` before installation?

Anyway, this requirement was added to fix incorrect bullet list rendering in documentation, you can safely remove this line from your `pyproject.toml` if you're not planning on building docs.

**Comment by AleXXL1986** [comment]
> Now I see the following:
> 
> ```shell
> % poetry install
> Installing dependencies from lock file
> Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
> 
>   SolverProblemError
> 
>   Because replay-rec depends on docutils (=0.16) which doesn't match any versions, version solving failed.
> ```
You can try to clear cache in poetry before update and install `poetry cache clear pypi --all`

**Comment by inpefess** [comment]
In the commit https://github.com/sberbank-ai-lab/RePlay/commit/d04a39aa659017aad47009af2b592882473ca414 `docutils` where added with no changes commited to `poetry.lock`. Probably someone edited `pyproject.toml` manually, without using `poetry add`.

Even when I add `docutils`, I see the following:

```sh
RuntimeError

  Unable to find installation candidates for torch (1.7.0)
```

**Comment by Darel13712** [comment]
I tried installing on a Mac and it installed successfully. It installed torch 1.10.0 though.

Here is my lock file (remove `.txt`), can you try it?
[poetry.lock.txt](https://github.com/sberbank-ai-lab/RePlay/files/7523070/poetry.lock.txt)

**Comment by inpefess** [comment]
In branch `test_397` I had no problems with installing with `poetry install` in Python 3.9.7. Thanks!
