### ISSUE TITLE
usersplitter by date returns less items in tests than required 

### ISSUE THREAD

**Issue by monkey0head** [sberbank-ai-lab/RePlay#45]
LAMA team reported that UserSplitter returns less items than required by the ``user_test_size`` with ``shuffle=False``. 

Users have sufficient interactions, but timestamps could be equal for all/ a part of interactions.

**Comment by Darel13712** [comment]
![](https://www.meme-arsenal.com/memes/9ff3ec359ede47b444a47a3708b2ea39.jpg)

**Comment by monkey0head** [comment]
We was not able to reproduce
