### ISSUE TITLE
`test_utils` fails

### ISSUE THREAD

**Issue by inpefess** [sberbank-ai-lab/RePlay#5]
`test_process_timestamp` fails (probably a timezone problem):

```
E   AssertionError: DataFrame.iloc[:, 0] (column name="str_") are different
E   
E   DataFrame.iloc[:, 0] (column name="str_") values are different (100.0 %)
E   [left]:  [2021-08-22T00:00:00.000000000, 2021-08-23T11:29:29.000000000, 2021-08-27T00:00:00.000000000]
E   [right]: [2021-08-21T22:00:00.000000000, 2021-08-23T09:29:29.000000000, 2021-08-26T22:00:00.000000000]
```

**Comment by Darel13712** [comment]
For whatever reason spark behaves differently locally and on github actions. If I fix test locally it fails on github and vice versa. 

It seems that when it creates timestamp with `createDataFrame` it is not the same when you do `from_unixtime`.

**Comment by AleXXL1986** [comment]
ask it in Moscow Spark and try to use java time function from context

**Comment by Darel13712** [comment]
Seems the problem was that spark was not the only entity using timezone. `datetime` module uses it too, that is why results differ when running locally and on github.
