### ISSUE TITLE
RePlay installation failed on Python 3.8.12

### ISSUE THREAD

**Issue by alexmryzhkov** [sberbank-ai-lab/RePlay#76]
I have tried to install Replay lib for python 3.8.12 with `pip install replay-rec` command into new virtual env. Pip was updated beforehand to 21.3.1 version.

The main problem was with implicit, which tried to find NVCC and CUDA on CPU machine.

Any ideas?

**Comment by Darel13712** [comment]
@monkey0head Did #83 solve the problem?
